### PR TITLE
Jx step git merge1

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by carlossg** [comment]
@pmuir the tests are failing in master for me with `make test` and I bisected it to this commit 

```
$ go test github.com/jenkins-x/jx/pkg/jx/cmd
# github.com/jenkins-x/jx/pkg/jx/cmd_test [github.com/jenkins-x/jx/pkg/jx/cmd.test]
pkg/jx/cmd/delete_app_test.go:19:17: undefined: CreateAppTestOptions
pkg/jx/cmd/delete_app_test.go:60:17: undefined: CreateAppTestOptions
pkg/jx/cmd/upgrade_apps_test.go:23:17: undefined: CreateAppTestOptions
pkg/jx/cmd/upgrade_apps_test.go:78:17: undefined: CreateAppTestOptions
pkg/jx/cmd/upgrade_apps_test.go:140:17: undefined: CreateAppTestOptions
FAIL	github.com/jenkins-x/jx/pkg/jx/cmd [build failed]
```
